@file:Suppress("unused", "UnstableApiUsage")

package dev.kikugie.kowoui

import io.wispforest.owo.ui.component.*
import io.wispforest.owo.ui.component.SlimSliderComponent.Axis
import io.wispforest.owo.ui.container.*
import io.wispforest.owo.ui.core.Component
import io.wispforest.owo.ui.core.Sizing
import net.minecraft.block.BlockState
import net.minecraft.block.entity.BlockEntity
import net.minecraft.client.texture.Sprite
import net.minecraft.client.util.SpriteIdentifier
import net.minecraft.entity.Entity
import net.minecraft.entity.EntityType
import net.minecraft.item.ItemStack
import net.minecraft.nbt.NbtCompound
import net.minecraft.text.Text
import net.minecraft.util.Identifier

/*
This is autogenerated, I wouldn't write this much
 */

// Base
inline fun stack(build: StackLayout.() -> Unit): StackLayout =
    Containers.stack(Sizing.content(), Sizing.content()).apply(build)

inline fun grid(rows: Int, columns: Int, build: GridLayout.() -> Unit): GridLayout =
    Containers.grid(Sizing.content(), Sizing.content(), rows, columns).apply(build)

inline fun horizontalFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.horizontalFlow(Sizing.content(), Sizing.content()).apply(build)

inline fun verticalFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.verticalFlow(Sizing.content(), Sizing.content()).apply(build)

inline fun ltrTextFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.ltrTextFlow(Sizing.content(), Sizing.content()).apply(build)

inline fun <T : Component> horizontalScroll(child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.horizontalScroll(Sizing.content(), Sizing.content(), child).apply(build)

inline fun <T : Component> verticalScroll(child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.verticalScroll(Sizing.content(), Sizing.content(), child).apply(build)

inline fun <T : Component> draggable(child: T, build: DraggableContainer<T>.() -> Unit): DraggableContainer<T> =
    Containers.draggable(Sizing.content(), Sizing.content(), child).apply(build)

inline fun collapsible(title: Text, expanded: Boolean, build: CollapsibleContainer.() -> Unit): CollapsibleContainer =
    Containers.collapsible(Sizing.content(), Sizing.content(), title, expanded).apply(build)

inline fun <T : Component> overlay(child: T, build: OverlayContainer<T>.() -> Unit): OverlayContainer<T> =
    Containers.overlay(child).apply(build)

inline fun <T : Component> renderEffect(child: T, build: RenderEffectWrapper<T>.() -> Unit): RenderEffectWrapper<T> =
    Containers.renderEffect(child).apply(build)

inline fun button(build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button("".text()) {}.apply(build)

inline fun button(text: Text, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button(text) {}.apply(build)

inline fun textBox(build: TextBoxComponent.() -> Unit): TextBoxComponent =
    Components.textBox(Sizing.content()).apply(build)

inline fun textArea(build: TextAreaComponent.() -> Unit): TextAreaComponent =
    Components.textArea(Sizing.content(), Sizing.content()).apply(build)

inline fun <T : Entity> entity(entity: T, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), entity).apply(build)

inline fun <T : Entity> entity(type: EntityType<T>, nbt: NbtCompound?, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), type, nbt).apply(build)

inline fun item(stack: ItemStack, build: ItemComponent.() -> Unit): ItemComponent =
    Components.item(stack).apply(build)

inline fun block(state: BlockState, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state).apply(build)

inline fun block(state: BlockState, blockEntity: BlockEntity, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, blockEntity).apply(build)

inline fun block(state: BlockState, nbt: NbtCompound?, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, nbt).apply(build)

inline fun label(build: LabelComponent.() -> Unit): LabelComponent =
    Components.label("".text()).apply(build)

inline fun label(text: Text, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label(text).apply(build)

inline fun checkbox(text: Text, build: CheckboxComponent.() -> Unit): CheckboxComponent =
    Components.checkbox(text).apply(build)

inline fun smallCheckbox(text: Text, build: SmallCheckboxComponent.() -> Unit): SmallCheckboxComponent =
    Components.smallCheckbox(text).apply(build)

inline fun slider(build: SliderComponent.() -> Unit): SliderComponent =
    Components.slider(Sizing.content()).apply(build)

inline fun slimSlider(axis: Axis, build: SlimSliderComponent.() -> Unit): SlimSliderComponent =
    Components.slimSlider(axis).apply(build)

inline fun discreteSlider(min: Double, max: Double, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), min, max).apply(build)

inline fun discreteSlider(range: ClosedFloatingPointRange<Double>, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), range.start, range.endInclusive).apply(build)

inline fun sprite(id: SpriteIdentifier, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(id).apply(build)

inline fun sprite(sprite: Sprite, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(sprite).apply(build)

inline fun texture(
    texture: Identifier,
    u: Int,
    v: Int,
    regionWidth: Int,
    regionHeight: Int,
    textureWidth: Int = 256,
    textureHeight: Int = 256,
    build: TextureComponent.() -> Unit,
): TextureComponent =
    Components.texture(texture, u, v, regionWidth, regionHeight, textureWidth, textureHeight).apply(build)

inline fun box(build: BoxComponent.() -> Unit): BoxComponent =
    Components.box(Sizing.content(), Sizing.content()).apply(build)

inline fun dropdown(build: DropdownComponent.() -> Unit): DropdownComponent =
    Components.dropdown(Sizing.content()).apply(build)

inline fun spacer(percent: Int = 100, build: SpacerComponent.() -> Unit): SpacerComponent =
    Components.spacer(percent).apply(build)

// Flow
inline fun FlowLayout.stack(build: StackLayout.() -> Unit): StackLayout =
    Containers.stack(Sizing.content(), Sizing.content()).apply(build).also { this@stack.child(it) }

inline fun FlowLayout.stack(index: Int, build: StackLayout.() -> Unit): StackLayout =
    Containers.stack(Sizing.content(), Sizing.content()).apply(build).also { this@stack.child(index, it) }

inline fun FlowLayout.grid(rows: Int, columns: Int, build: GridLayout.() -> Unit): GridLayout =
    Containers.grid(Sizing.content(), Sizing.content(), rows, columns).apply(build).also { this@grid.child(it) }

inline fun FlowLayout.grid(index: Int, rows: Int, columns: Int, build: GridLayout.() -> Unit): GridLayout =
    Containers.grid(Sizing.content(), Sizing.content(), rows, columns).apply(build).also { this@grid.child(index, it) }

inline fun FlowLayout.horizontalFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.horizontalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@horizontalFlow.child(it) }

inline fun FlowLayout.horizontalFlow(index: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.horizontalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@horizontalFlow.child(index, it) }

inline fun FlowLayout.verticalFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.verticalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@verticalFlow.child(it) }

inline fun FlowLayout.verticalFlow(index: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.verticalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@verticalFlow.child(index, it) }

inline fun FlowLayout.ltrTextFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.ltrTextFlow(Sizing.content(), Sizing.content()).apply(build).also { this@ltrTextFlow.child(it) }

inline fun FlowLayout.ltrTextFlow(index: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.ltrTextFlow(Sizing.content(), Sizing.content()).apply(build).also { this@ltrTextFlow.child(index, it) }

inline fun <T : Component> FlowLayout.horizontalScroll(child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.horizontalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@horizontalScroll.child(it) }

inline fun <T : Component> FlowLayout.horizontalScroll(index: Int, child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.horizontalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@horizontalScroll.child(index, it) }

inline fun <T : Component> FlowLayout.verticalScroll(child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.verticalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@verticalScroll.child(it) }

inline fun <T : Component> FlowLayout.verticalScroll(index: Int, child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.verticalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@verticalScroll.child(index, it) }

inline fun <T : Component> FlowLayout.draggable(child: T, build: DraggableContainer<T>.() -> Unit): DraggableContainer<T> =
    Containers.draggable(Sizing.content(), Sizing.content(), child).apply(build).also { this@draggable.child(it) }

inline fun <T : Component> FlowLayout.draggable(index: Int, child: T, build: DraggableContainer<T>.() -> Unit): DraggableContainer<T> =
    Containers.draggable(Sizing.content(), Sizing.content(), child).apply(build).also { this@draggable.child(index, it) }

inline fun FlowLayout.collapsible(title: Text, expanded: Boolean, build: CollapsibleContainer.() -> Unit): CollapsibleContainer =
    Containers.collapsible(Sizing.content(), Sizing.content(), title, expanded).apply(build).also { this@collapsible.child(it) }

inline fun FlowLayout.collapsible(index: Int, title: Text, expanded: Boolean, build: CollapsibleContainer.() -> Unit): CollapsibleContainer =
    Containers.collapsible(Sizing.content(), Sizing.content(), title, expanded).apply(build).also { this@collapsible.child(index, it) }

inline fun <T : Component> FlowLayout.overlay(child: T, build: OverlayContainer<T>.() -> Unit): OverlayContainer<T> =
    Containers.overlay(child).apply(build).also { this@overlay.child(it) }

inline fun <T : Component> FlowLayout.overlay(index: Int, child: T, build: OverlayContainer<T>.() -> Unit): OverlayContainer<T> =
    Containers.overlay(child).apply(build).also { this@overlay.child(index, it) }

inline fun <T : Component> FlowLayout.renderEffect(child: T, build: RenderEffectWrapper<T>.() -> Unit): RenderEffectWrapper<T> =
    Containers.renderEffect(child).apply(build).also { this@renderEffect.child(it) }

inline fun <T : Component> FlowLayout.renderEffect(index: Int, child: T, build: RenderEffectWrapper<T>.() -> Unit): RenderEffectWrapper<T> =
    Containers.renderEffect(child).apply(build).also { this@renderEffect.child(index, it) }

inline fun FlowLayout.button(build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button("".text()) {}.apply(build).also { this@button.child(it) }

inline fun FlowLayout.button(index: Int, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button("".text()) {}.apply(build).also { this@button.child(index, it) }

inline fun FlowLayout.button(text: Text, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button(text) {}.apply(build).also { this@button.child(it) }

inline fun FlowLayout.button(index: Int, text: Text, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button(text) {}.apply(build).also { this@button.child(index, it) }

inline fun FlowLayout.textBox(build: TextBoxComponent.() -> Unit): TextBoxComponent =
    Components.textBox(Sizing.content()).apply(build).also { this@textBox.child(it) }

inline fun FlowLayout.textBox(index: Int, build: TextBoxComponent.() -> Unit): TextBoxComponent =
    Components.textBox(Sizing.content()).apply(build).also { this@textBox.child(index, it) }

inline fun FlowLayout.textArea(build: TextAreaComponent.() -> Unit): TextAreaComponent =
    Components.textArea(Sizing.content(), Sizing.content()).apply(build).also { this@textArea.child(it) }

inline fun FlowLayout.textArea(index: Int, build: TextAreaComponent.() -> Unit): TextAreaComponent =
    Components.textArea(Sizing.content(), Sizing.content()).apply(build).also { this@textArea.child(index, it) }

inline fun <T : Entity> FlowLayout.entity(entity: T, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), entity).apply(build).also { this@entity.child(it) }

inline fun <T : Entity> FlowLayout.entity(index: Int, entity: T, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), entity).apply(build).also { this@entity.child(index, it) }

inline fun <T : Entity> FlowLayout.entity(type: EntityType<T>, nbt: NbtCompound?, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), type, nbt).apply(build).also { this@entity.child(it) }

inline fun <T : Entity> FlowLayout.entity(index: Int, type: EntityType<T>, nbt: NbtCompound?, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), type, nbt).apply(build).also { this@entity.child(index, it) }

inline fun FlowLayout.item(stack: ItemStack, build: ItemComponent.() -> Unit): ItemComponent =
    Components.item(stack).apply(build).also { this@item.child(it) }

inline fun FlowLayout.item(index: Int, stack: ItemStack, build: ItemComponent.() -> Unit): ItemComponent =
    Components.item(stack).apply(build).also { this@item.child(index, it) }

inline fun FlowLayout.block(state: BlockState, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state).apply(build).also { this@block.child(it) }

inline fun FlowLayout.block(index: Int, state: BlockState, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state).apply(build).also { this@block.child(index, it) }

inline fun FlowLayout.block(state: BlockState, blockEntity: BlockEntity, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, blockEntity).apply(build).also { this@block.child(it) }

inline fun FlowLayout.block(index: Int, state: BlockState, blockEntity: BlockEntity, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, blockEntity).apply(build).also { this@block.child(index, it) }

inline fun FlowLayout.block(state: BlockState, nbt: NbtCompound?, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, nbt).apply(build).also { this@block.child(it) }

inline fun FlowLayout.block(index: Int, state: BlockState, nbt: NbtCompound?, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, nbt).apply(build).also { this@block.child(index, it) }

inline fun FlowLayout.label(build: LabelComponent.() -> Unit): LabelComponent =
    Components.label("".text()).apply(build).also { this@label.child(it) }

inline fun FlowLayout.label(index: Int, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label("".text()).apply(build).also { this@label.child(index, it) }

inline fun FlowLayout.label(text: Text, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label(text).apply(build).also { this@label.child(it) }

inline fun FlowLayout.label(index: Int, text: Text, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label(text).apply(build).also { this@label.child(index, it) }

inline fun FlowLayout.checkbox(text: Text, build: CheckboxComponent.() -> Unit): CheckboxComponent =
    Components.checkbox(text).apply(build).also { this@checkbox.child(it) }

inline fun FlowLayout.checkbox(index: Int, text: Text, build: CheckboxComponent.() -> Unit): CheckboxComponent =
    Components.checkbox(text).apply(build).also { this@checkbox.child(index, it) }

inline fun FlowLayout.smallCheckbox(text: Text, build: SmallCheckboxComponent.() -> Unit): SmallCheckboxComponent =
    Components.smallCheckbox(text).apply(build).also { this@smallCheckbox.child(it) }

inline fun FlowLayout.smallCheckbox(index: Int, text: Text, build: SmallCheckboxComponent.() -> Unit): SmallCheckboxComponent =
    Components.smallCheckbox(text).apply(build).also { this@smallCheckbox.child(index, it) }

inline fun FlowLayout.slider(build: SliderComponent.() -> Unit): SliderComponent =
    Components.slider(Sizing.content()).apply(build).also { this@slider.child(it) }

inline fun FlowLayout.slider(index: Int, build: SliderComponent.() -> Unit): SliderComponent =
    Components.slider(Sizing.content()).apply(build).also { this@slider.child(index, it) }

inline fun FlowLayout.slimSlider(axis: Axis, build: SlimSliderComponent.() -> Unit): SlimSliderComponent =
    Components.slimSlider(axis).apply(build).also { this@slimSlider.child(it) }

inline fun FlowLayout.slimSlider(index: Int, axis: Axis, build: SlimSliderComponent.() -> Unit): SlimSliderComponent =
    Components.slimSlider(axis).apply(build).also { this@slimSlider.child(index, it) }

inline fun FlowLayout.discreteSlider(min: Double, max: Double, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), min, max).apply(build).also { this@discreteSlider.child(it) }

inline fun FlowLayout.discreteSlider(index: Int, min: Double, max: Double, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), min, max).apply(build).also { this@discreteSlider.child(index, it) }

inline fun FlowLayout.discreteSlider(range: ClosedFloatingPointRange<Double>, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), range.start, range.endInclusive).apply(build).also { this@discreteSlider.child(it) }

inline fun FlowLayout.discreteSlider(index: Int, range: ClosedFloatingPointRange<Double>, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), range.start, range.endInclusive).apply(build).also { this@discreteSlider.child(index, it) }

inline fun FlowLayout.sprite(id: SpriteIdentifier, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(id).apply(build).also { this@sprite.child(it) }

inline fun FlowLayout.sprite(index: Int, id: SpriteIdentifier, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(id).apply(build).also { this@sprite.child(index, it) }

inline fun FlowLayout.sprite(sprite: Sprite, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(sprite).apply(build).also { this@sprite.child(it) }

inline fun FlowLayout.sprite(index: Int, sprite: Sprite, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(sprite).apply(build).also { this@sprite.child(index, it) }

inline fun FlowLayout.texture(
    texture: Identifier,
    u: Int,
    v: Int,
    regionWidth: Int,
    regionHeight: Int,
    textureWidth: Int = 256,
    textureHeight: Int = 256,
    build: TextureComponent.() -> Unit,
): TextureComponent =
    Components.texture(texture, u, v, regionWidth, regionHeight, textureWidth, textureHeight).apply(build).also { this@texture.child(it) }

inline fun FlowLayout.texture(
    index: Int,
    texture: Identifier,
    u: Int,
    v: Int,
    regionWidth: Int,
    regionHeight: Int,
    textureWidth: Int = 256,
    textureHeight: Int = 256,
    build: TextureComponent.() -> Unit,
): TextureComponent =
    Components.texture(texture, u, v, regionWidth, regionHeight, textureWidth, textureHeight).apply(build).also { this@texture.child(index, it) }

inline fun FlowLayout.box(build: BoxComponent.() -> Unit): BoxComponent =
    Components.box(Sizing.content(), Sizing.content()).apply(build).also { this@box.child(it) }

inline fun FlowLayout.box(index: Int, build: BoxComponent.() -> Unit): BoxComponent =
    Components.box(Sizing.content(), Sizing.content()).apply(build).also { this@box.child(index, it) }

inline fun FlowLayout.dropdown(build: DropdownComponent.() -> Unit): DropdownComponent =
    Components.dropdown(Sizing.content()).apply(build).also { this@dropdown.child(it) }

inline fun FlowLayout.dropdown(index: Int, build: DropdownComponent.() -> Unit): DropdownComponent =
    Components.dropdown(Sizing.content()).apply(build).also { this@dropdown.child(index, it) }

inline fun FlowLayout.spacer(percent: Int = 100, build: SpacerComponent.() -> Unit): SpacerComponent =
    Components.spacer(percent).apply(build).also { this@spacer.child(it) }

inline fun FlowLayout.spacer(index: Int, percent: Int = 100, build: SpacerComponent.() -> Unit): SpacerComponent =
    Components.spacer(percent).apply(build).also { this@spacer.child(index, it) }

// Stack
inline fun StackLayout.stack(build: StackLayout.() -> Unit): StackLayout =
    Containers.stack(Sizing.content(), Sizing.content()).apply(build).also { this@stack.child(it) }

inline fun StackLayout.stack(index: Int, build: StackLayout.() -> Unit): StackLayout =
    Containers.stack(Sizing.content(), Sizing.content()).apply(build).also { this@stack.child(index, it) }

inline fun StackLayout.grid(rows: Int, columns: Int, build: GridLayout.() -> Unit): GridLayout =
    Containers.grid(Sizing.content(), Sizing.content(), rows, columns).apply(build).also { this@grid.child(it) }

inline fun StackLayout.grid(index: Int, rows: Int, columns: Int, build: GridLayout.() -> Unit): GridLayout =
    Containers.grid(Sizing.content(), Sizing.content(), rows, columns).apply(build).also { this@grid.child(index, it) }

inline fun StackLayout.horizontalFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.horizontalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@horizontalFlow.child(it) }

inline fun StackLayout.horizontalFlow(index: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.horizontalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@horizontalFlow.child(index, it) }

inline fun StackLayout.verticalFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.verticalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@verticalFlow.child(it) }

inline fun StackLayout.verticalFlow(index: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.verticalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@verticalFlow.child(index, it) }

inline fun StackLayout.ltrTextFlow(build: FlowLayout.() -> Unit): FlowLayout =
    Containers.ltrTextFlow(Sizing.content(), Sizing.content()).apply(build).also { this@ltrTextFlow.child(it) }

inline fun StackLayout.ltrTextFlow(index: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.ltrTextFlow(Sizing.content(), Sizing.content()).apply(build).also { this@ltrTextFlow.child(index, it) }

inline fun <T : Component> StackLayout.horizontalScroll(child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.horizontalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@horizontalScroll.child(it) }

inline fun <T : Component> StackLayout.horizontalScroll(index: Int, child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.horizontalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@horizontalScroll.child(index, it) }

inline fun <T : Component> StackLayout.verticalScroll(child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.verticalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@verticalScroll.child(it) }

inline fun <T : Component> StackLayout.verticalScroll(index: Int, child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.verticalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@verticalScroll.child(index, it) }

inline fun <T : Component> StackLayout.draggable(child: T, build: DraggableContainer<T>.() -> Unit): DraggableContainer<T> =
    Containers.draggable(Sizing.content(), Sizing.content(), child).apply(build).also { this@draggable.child(it) }

inline fun <T : Component> StackLayout.draggable(index: Int, child: T, build: DraggableContainer<T>.() -> Unit): DraggableContainer<T> =
    Containers.draggable(Sizing.content(), Sizing.content(), child).apply(build).also { this@draggable.child(index, it) }

inline fun StackLayout.collapsible(title: Text, expanded: Boolean, build: CollapsibleContainer.() -> Unit): CollapsibleContainer =
    Containers.collapsible(Sizing.content(), Sizing.content(), title, expanded).apply(build).also { this@collapsible.child(it) }

inline fun StackLayout.collapsible(index: Int, title: Text, expanded: Boolean, build: CollapsibleContainer.() -> Unit): CollapsibleContainer =
    Containers.collapsible(Sizing.content(), Sizing.content(), title, expanded).apply(build).also { this@collapsible.child(index, it) }

inline fun <T : Component> StackLayout.overlay(child: T, build: OverlayContainer<T>.() -> Unit): OverlayContainer<T> =
    Containers.overlay(child).apply(build).also { this@overlay.child(it) }

inline fun <T : Component> StackLayout.overlay(index: Int, child: T, build: OverlayContainer<T>.() -> Unit): OverlayContainer<T> =
    Containers.overlay(child).apply(build).also { this@overlay.child(index, it) }

inline fun <T : Component> StackLayout.renderEffect(child: T, build: RenderEffectWrapper<T>.() -> Unit): RenderEffectWrapper<T> =
    Containers.renderEffect(child).apply(build).also { this@renderEffect.child(it) }

inline fun <T : Component> StackLayout.renderEffect(index: Int, child: T, build: RenderEffectWrapper<T>.() -> Unit): RenderEffectWrapper<T> =
    Containers.renderEffect(child).apply(build).also { this@renderEffect.child(index, it) }

inline fun StackLayout.button(build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button("".text()) {}.apply(build).also { this@button.child(it) }

inline fun StackLayout.button(index: Int, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button("".text()) {}.apply(build).also { this@button.child(index, it) }

inline fun StackLayout.button(text: Text, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button(text) {}.apply(build).also { this@button.child(it) }

inline fun StackLayout.button(index: Int, text: Text, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button(text) {}.apply(build).also { this@button.child(index, it) }

inline fun StackLayout.textBox(build: TextBoxComponent.() -> Unit): TextBoxComponent =
    Components.textBox(Sizing.content()).apply(build).also { this@textBox.child(it) }

inline fun StackLayout.textBox(index: Int, build: TextBoxComponent.() -> Unit): TextBoxComponent =
    Components.textBox(Sizing.content()).apply(build).also { this@textBox.child(index, it) }

inline fun StackLayout.textArea(build: TextAreaComponent.() -> Unit): TextAreaComponent =
    Components.textArea(Sizing.content(), Sizing.content()).apply(build).also { this@textArea.child(it) }

inline fun StackLayout.textArea(index: Int, build: TextAreaComponent.() -> Unit): TextAreaComponent =
    Components.textArea(Sizing.content(), Sizing.content()).apply(build).also { this@textArea.child(index, it) }

inline fun <T : Entity> StackLayout.entity(entity: T, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), entity).apply(build).also { this@entity.child(it) }

inline fun <T : Entity> StackLayout.entity(index: Int, entity: T, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), entity).apply(build).also { this@entity.child(index, it) }

inline fun <T : Entity> StackLayout.entity(type: EntityType<T>, nbt: NbtCompound?, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), type, nbt).apply(build).also { this@entity.child(it) }

inline fun <T : Entity> StackLayout.entity(index: Int, type: EntityType<T>, nbt: NbtCompound?, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), type, nbt).apply(build).also { this@entity.child(index, it) }

inline fun StackLayout.item(stack: ItemStack, build: ItemComponent.() -> Unit): ItemComponent =
    Components.item(stack).apply(build).also { this@item.child(it) }

inline fun StackLayout.item(index: Int, stack: ItemStack, build: ItemComponent.() -> Unit): ItemComponent =
    Components.item(stack).apply(build).also { this@item.child(index, it) }

inline fun StackLayout.block(state: BlockState, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state).apply(build).also { this@block.child(it) }

inline fun StackLayout.block(index: Int, state: BlockState, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state).apply(build).also { this@block.child(index, it) }

inline fun StackLayout.block(state: BlockState, blockEntity: BlockEntity, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, blockEntity).apply(build).also { this@block.child(it) }

inline fun StackLayout.block(index: Int, state: BlockState, blockEntity: BlockEntity, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, blockEntity).apply(build).also { this@block.child(index, it) }

inline fun StackLayout.block(state: BlockState, nbt: NbtCompound?, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, nbt).apply(build).also { this@block.child(it) }

inline fun StackLayout.block(index: Int, state: BlockState, nbt: NbtCompound?, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, nbt).apply(build).also { this@block.child(index, it) }

inline fun StackLayout.label(build: LabelComponent.() -> Unit): LabelComponent =
    Components.label("".text()).apply(build).also { this@label.child(it) }

inline fun StackLayout.label(index: Int, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label("".text()).apply(build).also { this@label.child(index, it) }

inline fun StackLayout.label(text: Text, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label(text).apply(build).also { this@label.child(it) }

inline fun StackLayout.label(index: Int, text: Text, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label(text).apply(build).also { this@label.child(index, it) }

inline fun StackLayout.checkbox(text: Text, build: CheckboxComponent.() -> Unit): CheckboxComponent =
    Components.checkbox(text).apply(build).also { this@checkbox.child(it) }

inline fun StackLayout.checkbox(index: Int, text: Text, build: CheckboxComponent.() -> Unit): CheckboxComponent =
    Components.checkbox(text).apply(build).also { this@checkbox.child(index, it) }

inline fun StackLayout.smallCheckbox(text: Text, build: SmallCheckboxComponent.() -> Unit): SmallCheckboxComponent =
    Components.smallCheckbox(text).apply(build).also { this@smallCheckbox.child(it) }

inline fun StackLayout.smallCheckbox(index: Int, text: Text, build: SmallCheckboxComponent.() -> Unit): SmallCheckboxComponent =
    Components.smallCheckbox(text).apply(build).also { this@smallCheckbox.child(index, it) }

inline fun StackLayout.slider(build: SliderComponent.() -> Unit): SliderComponent =
    Components.slider(Sizing.content()).apply(build).also { this@slider.child(it) }

inline fun StackLayout.slider(index: Int, build: SliderComponent.() -> Unit): SliderComponent =
    Components.slider(Sizing.content()).apply(build).also { this@slider.child(index, it) }

inline fun StackLayout.slimSlider(axis: Axis, build: SlimSliderComponent.() -> Unit): SlimSliderComponent =
    Components.slimSlider(axis).apply(build).also { this@slimSlider.child(it) }

inline fun StackLayout.slimSlider(index: Int, axis: Axis, build: SlimSliderComponent.() -> Unit): SlimSliderComponent =
    Components.slimSlider(axis).apply(build).also { this@slimSlider.child(index, it) }

inline fun StackLayout.discreteSlider(min: Double, max: Double, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), min, max).apply(build).also { this@discreteSlider.child(it) }

inline fun StackLayout.discreteSlider(index: Int, min: Double, max: Double, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), min, max).apply(build).also { this@discreteSlider.child(index, it) }

inline fun StackLayout.discreteSlider(range: ClosedFloatingPointRange<Double>, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), range.start, range.endInclusive).apply(build).also { this@discreteSlider.child(it) }

inline fun StackLayout.discreteSlider(index: Int, range: ClosedFloatingPointRange<Double>, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), range.start, range.endInclusive).apply(build).also { this@discreteSlider.child(index, it) }

inline fun StackLayout.sprite(id: SpriteIdentifier, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(id).apply(build).also { this@sprite.child(it) }

inline fun StackLayout.sprite(index: Int, id: SpriteIdentifier, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(id).apply(build).also { this@sprite.child(index, it) }

inline fun StackLayout.sprite(sprite: Sprite, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(sprite).apply(build).also { this@sprite.child(it) }

inline fun StackLayout.sprite(index: Int, sprite: Sprite, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(sprite).apply(build).also { this@sprite.child(index, it) }

inline fun StackLayout.texture(
    texture: Identifier,
    u: Int,
    v: Int,
    regionWidth: Int,
    regionHeight: Int,
    textureWidth: Int = 256,
    textureHeight: Int = 256,
    build: TextureComponent.() -> Unit,
): TextureComponent =
    Components.texture(texture, u, v, regionWidth, regionHeight, textureWidth, textureHeight).apply(build).also { this@texture.child(it) }

inline fun StackLayout.texture(
    index: Int,
    texture: Identifier,
    u: Int,
    v: Int,
    regionWidth: Int,
    regionHeight: Int,
    textureWidth: Int = 256,
    textureHeight: Int = 256,
    build: TextureComponent.() -> Unit,
): TextureComponent =
    Components.texture(texture, u, v, regionWidth, regionHeight, textureWidth, textureHeight).apply(build).also { this@texture.child(index, it) }

inline fun StackLayout.box(build: BoxComponent.() -> Unit): BoxComponent =
    Components.box(Sizing.content(), Sizing.content()).apply(build).also { this@box.child(it) }

inline fun StackLayout.box(index: Int, build: BoxComponent.() -> Unit): BoxComponent =
    Components.box(Sizing.content(), Sizing.content()).apply(build).also { this@box.child(index, it) }

inline fun StackLayout.dropdown(build: DropdownComponent.() -> Unit): DropdownComponent =
    Components.dropdown(Sizing.content()).apply(build).also { this@dropdown.child(it) }

inline fun StackLayout.dropdown(index: Int, build: DropdownComponent.() -> Unit): DropdownComponent =
    Components.dropdown(Sizing.content()).apply(build).also { this@dropdown.child(index, it) }

inline fun StackLayout.spacer(percent: Int = 100, build: SpacerComponent.() -> Unit): SpacerComponent =
    Components.spacer(percent).apply(build).also { this@spacer.child(it) }

inline fun StackLayout.spacer(index: Int, percent: Int = 100, build: SpacerComponent.() -> Unit): SpacerComponent =
    Components.spacer(percent).apply(build).also { this@spacer.child(index, it) }

// Grid
inline fun GridLayout.stack(row: Int, column: Int, build: StackLayout.() -> Unit): StackLayout =
    Containers.stack(Sizing.content(), Sizing.content()).apply(build).also { this@stack.child(it, row, column) }

inline fun GridLayout.grid(row: Int, column: Int, rows: Int, columns: Int, build: GridLayout.() -> Unit): GridLayout =
    Containers.grid(Sizing.content(), Sizing.content(), rows, columns).apply(build).also { this@grid.child(it, row, column) }

inline fun GridLayout.horizontalFlow(row: Int, column: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.horizontalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@horizontalFlow.child(it, row, column) }

inline fun GridLayout.verticalFlow(row: Int, column: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.verticalFlow(Sizing.content(), Sizing.content()).apply(build).also { this@verticalFlow.child(it, row, column) }

inline fun GridLayout.ltrTextFlow(row: Int, column: Int, build: FlowLayout.() -> Unit): FlowLayout =
    Containers.ltrTextFlow(Sizing.content(), Sizing.content()).apply(build).also { this@ltrTextFlow.child(it, row, column) }

inline fun <T : Component> GridLayout.horizontalScroll(row: Int, column: Int, child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.horizontalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@horizontalScroll.child(it, row, column) }

inline fun <T : Component> GridLayout.verticalScroll(row: Int, column: Int, child: T, build: ScrollContainer<T>.() -> Unit): ScrollContainer<T> =
    Containers.verticalScroll(Sizing.content(), Sizing.content(), child).apply(build).also { this@verticalScroll.child(it, row, column) }

inline fun <T : Component> GridLayout.draggable(row: Int, column: Int, child: T, build: DraggableContainer<T>.() -> Unit): DraggableContainer<T> =
    Containers.draggable(Sizing.content(), Sizing.content(), child).apply(build).also { this@draggable.child(it, row, column) }

inline fun GridLayout.collapsible(row: Int, column: Int, title: Text, expanded: Boolean, build: CollapsibleContainer.() -> Unit): CollapsibleContainer =
    Containers.collapsible(Sizing.content(), Sizing.content(), title, expanded).apply(build).also { this@collapsible.child(it, row, column) }

inline fun <T : Component> GridLayout.overlay(row: Int, column: Int, child: T, build: OverlayContainer<T>.() -> Unit): OverlayContainer<T> =
    Containers.overlay(child).apply(build).also { this@overlay.child(it, row, column) }

inline fun <T : Component> GridLayout.renderEffect(row: Int, column: Int, child: T, build: RenderEffectWrapper<T>.() -> Unit): RenderEffectWrapper<T> =
    Containers.renderEffect(child).apply(build).also { this@renderEffect.child(it, row, column) }

inline fun GridLayout.button(row: Int, column: Int, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button("".text()) {}.apply(build).also { this@button.child(it, row, column) }

inline fun GridLayout.button(row: Int, column: Int, text: Text, build: ButtonComponent.() -> Unit): ButtonComponent =
    Components.button(text) {}.apply(build).also { this@button.child(it, row, column) }

inline fun GridLayout.textBox(row: Int, column: Int, build: TextBoxComponent.() -> Unit): TextBoxComponent =
    Components.textBox(Sizing.content()).apply(build).also { this@textBox.child(it, row, column) }

inline fun GridLayout.textArea(row: Int, column: Int, build: TextAreaComponent.() -> Unit): TextAreaComponent =
    Components.textArea(Sizing.content(), Sizing.content()).apply(build).also { this@textArea.child(it, row, column) }

inline fun <T : Entity> GridLayout.entity(row: Int, column: Int, entity: T, build: EntityComponent<T>.() -> Unit): EntityComponent<T> =
    Components.entity(Sizing.content(), entity).apply(build).also { this@entity.child(it, row, column) }

inline fun <T : Entity> GridLayout.entity(
    row: Int,
    column: Int,
    type: EntityType<T>,
    nbt: NbtCompound?,
    build: EntityComponent<T>.() -> Unit,
): EntityComponent<T> =
    Components.entity(Sizing.content(), type, nbt).apply(build).also { this@entity.child(it, row, column) }

inline fun GridLayout.item(row: Int, column: Int, stack: ItemStack, build: ItemComponent.() -> Unit): ItemComponent =
    Components.item(stack).apply(build).also { this@item.child(it, row, column) }

inline fun GridLayout.block(row: Int, column: Int, state: BlockState, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state).apply(build).also { this@block.child(it, row, column) }

inline fun GridLayout.block(row: Int, column: Int, state: BlockState, blockEntity: BlockEntity, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, blockEntity).apply(build).also { this@block.child(it, row, column) }

inline fun GridLayout.block(row: Int, column: Int, state: BlockState, nbt: NbtCompound?, build: BlockComponent.() -> Unit): BlockComponent =
    Components.block(state, nbt).apply(build).also { this@block.child(it, row, column) }

inline fun GridLayout.label(row: Int, column: Int, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label("".text()).apply(build).also { this@label.child(it, row, column) }

inline fun GridLayout.label(row: Int, column: Int, text: Text, build: LabelComponent.() -> Unit): LabelComponent =
    Components.label(text).apply(build).also { this@label.child(it, row, column) }

inline fun GridLayout.checkbox(row: Int, column: Int, text: Text, build: CheckboxComponent.() -> Unit): CheckboxComponent =
    Components.checkbox(text).apply(build).also { this@checkbox.child(it, row, column) }

inline fun GridLayout.smallCheckbox(row: Int, column: Int, text: Text, build: SmallCheckboxComponent.() -> Unit): SmallCheckboxComponent =
    Components.smallCheckbox(text).apply(build).also { this@smallCheckbox.child(it, row, column) }

inline fun GridLayout.slider(row: Int, column: Int, build: SliderComponent.() -> Unit): SliderComponent =
    Components.slider(Sizing.content()).apply(build).also { this@slider.child(it, row, column) }

inline fun GridLayout.slimSlider(row: Int, column: Int, axis: Axis, build: SlimSliderComponent.() -> Unit): SlimSliderComponent =
    Components.slimSlider(axis).apply(build).also { this@slimSlider.child(it, row, column) }

inline fun GridLayout.discreteSlider(row: Int, column: Int, min: Double, max: Double, build: DiscreteSliderComponent.() -> Unit): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), min, max).apply(build).also { this@discreteSlider.child(it, row, column) }

inline fun GridLayout.discreteSlider(
    row: Int,
    column: Int,
    range: ClosedFloatingPointRange<Double>,
    build: DiscreteSliderComponent.() -> Unit,
): DiscreteSliderComponent =
    Components.discreteSlider(Sizing.content(), range.start, range.endInclusive).apply(build).also { this@discreteSlider.child(it, row, column) }

inline fun GridLayout.sprite(row: Int, column: Int, id: SpriteIdentifier, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(id).apply(build).also { this@sprite.child(it, row, column) }

inline fun GridLayout.sprite(row: Int, column: Int, sprite: Sprite, build: SpriteComponent.() -> Unit): SpriteComponent =
    Components.sprite(sprite).apply(build).also { this@sprite.child(it, row, column) }

inline fun GridLayout.texture(
    row: Int,
    column: Int,
    texture: Identifier,
    u: Int,
    v: Int,
    regionWidth: Int,
    regionHeight: Int,
    textureWidth: Int = 256,
    textureHeight: Int = 256,
    build: TextureComponent.() -> Unit,
): TextureComponent =
    Components.texture(texture, u, v, regionWidth, regionHeight, textureWidth, textureHeight).apply(build).also { this@texture.child(it, row, column) }

inline fun GridLayout.box(row: Int, column: Int, build: BoxComponent.() -> Unit): BoxComponent =
    Components.box(Sizing.content(), Sizing.content()).apply(build).also { this@box.child(it, row, column) }

inline fun GridLayout.dropdown(row: Int, column: Int, build: DropdownComponent.() -> Unit): DropdownComponent =
    Components.dropdown(Sizing.content()).apply(build).also { this@dropdown.child(it, row, column) }

inline fun GridLayout.spacer(row: Int, column: Int, percent: Int = 100, build: SpacerComponent.() -> Unit): SpacerComponent =
    Components.spacer(percent).apply(build).also { this@spacer.child(it, row, column) }