fabric.loom.multiProjectOptimisation=true
org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

id=soundboard
name=Soundboard Core
version=0.7.1

kowoui.id=kowoui
kowoui.name=Kotlin OwO UI
kowoui.version=0.3.0

group=dev.kikugie

mcdep=1.21.4
flk=>=0.13
owolib=~0.12

mcversions=1.21.4

release=stable